[package]
name = "definition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
anyhow = "1.0.75"
xml-rs = "0.8.19"
convert_case = "0.6.0"
