[package]
name = "fhir-resource-r5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0.1.37", features = [] }
fhir-rs = { path = "../fhir-rs"}
anyhow = "1.0.75"