[package]
name = "transform"
version = "0.1.0"
edition = "2021"

[dependencies]
fhir-rs = { path = "../../fhir-rs"}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
anyhow = "1.0.75"
chrono = "0.4.31"